INSERT INTO users(active,age,birth_date,name,gender) VALUES (1,32,STR_TO_DATE('01-01-1990', '%d-%m-%Y'),'MARCOS HUERTAS PEREZ','M');
INSERT INTO users(active,age,birth_date,name,gender) VALUES (1,26,STR_TO_DATE('05-04-1996', '%d-%m-%Y'),'PEDRO PABLO GONZALEZ MURILLO','M');
INSERT INTO users(active,age,birth_date,name,gender) VALUES (1,26,STR_TO_DATE('02-08-1996', '%d-%m-%Y'),'MARCOS MURILLO GONZALEZ','M');
INSERT INTO users(active,age,birth_date,name,gender) VALUES (1,42,STR_TO_DATE('12-05-1980', '%d-%m-%Y'),'DIANA MARCELA PEREZ HUERTAS','F');
INSERT INTO users(active,age,birth_date,name,gender) VALUES (1,42,STR_TO_DATE('03-02-1980', '%d-%m-%Y'),'ARTURO RAFAEL LUGO GOMEZ','M');
INSERT INTO users(active,age,birth_date,name,gender) VALUES (1,26,STR_TO_DATE('02-08-1996', '%d-%m-%Y'),'MARCOS ARTURO GOMEZ LUGO','M');
INSERT INTO users(active,age,birth_date,name,gender) VALUES (1,22,STR_TO_DATE('05-03-1999', '%d-%m-%Y'),'CAROLINA ECHAVARRIA DE BRIGARTH','F');
INSERT INTO users(active,age,birth_date,name,gender) VALUES (1,29,STR_TO_DATE('12-09-1993', '%d-%m-%Y'),'SANDRA JOHANNA DURAN CHACON','F');
INSERT INTO users(active,age,birth_date,name,gender) VALUES (1,29,STR_TO_DATE('05-09-1993', '%d-%m-%Y'),'JESUS ERNESTO LOPEZ TELLEZ','M');
INSERT INTO users(active,age,birth_date,name,gender) VALUES (1,26,STR_TO_DATE('05-04-1996', '%d-%m-%Y'),'LADY ESMERALDA PEREZ PEREZ','F');
INSERT INTO users(active,age,birth_date,name,gender) VALUES (1,33,STR_TO_DATE('12-11-1988', '%d-%m-%Y'),'STIVEN FORERO ARDILA','M');
INSERT INTO users(active,age,birth_date,name,gender) VALUES (1,33,STR_TO_DATE('05-06-1988', '%d-%m-%Y'),'JUAN CARLOS LOZANO MEDINA','M');
INSERT INTO users(active,age,birth_date,name,gender) VALUES (1,51,STR_TO_DATE('08-02-1971', '%d-%m-%Y'),'PEDRO ANTONIO CHACON SUAREZ','M');
INSERT INTO users(active,age,birth_date,name,gender) VALUES (1,48,STR_TO_DATE('13-07-1974', '%d-%m-%Y'),'SILVERIO DE JESUS SANABRIA CEPEDA','M');
INSERT INTO users(active,age,birth_date,name,gender) VALUES (1,33,STR_TO_DATE('12-11-1988', '%d-%m-%Y'),'LILIA YOJANNA BARBOSA PICO','F');
